#spring.jmx.enabled=true
spring.application.name=Distributed KV Store
server.port = 8081

cluster.nodes = localhost:8080,localhost:8081,localhost:8082
cluster.replication.factor=2
#
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.metrics.enabled=true
management.endpoint.prmetheus.enabled=true
management.endpoint.health.show-details=always
management.endpoint.metrics.show-details=always
